In [1]:
L=list(range(10))

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [4]:
L2 = [str(c) for cin L]

SyntaxError: invalid syntax (<ipython-input-4-7d36e27dc58d>, line 1)

In [5]:
L2 = [str(c) for c in L]

In [6]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [true(item) for item in L3]

NameError: name 'L3' is not defined

In [9]:
L3 = [True, '2', 3.0, 4]

In [10]:
[type(item) for item in L3]

[bool, str, float, int]

In [11]:
import array

In [12]:
L = list(range(10))
A = array.array('i', L)

In [13]:
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
import numpy as np

In [15]:
integer array:

SyntaxError: invalid syntax (<ipython-input-15-ac77fc26810c>, line 1)

In [16]:
# integer array:

In [17]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [18]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
array([1, 2, 3, 4], dtype = 'float32')

TypeError: 'module' object is not callable

In [20]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
# nested lists result in multidimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
np.array([range(i, i+2) for i in [2, 4, 6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [23]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=in)

SyntaxError: invalid syntax (<ipython-input-23-73ca0a7fe2e2>, line 2)

In [24]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# create a 3*5 floating-point array filled with 1s 
np.ones((3, 5), type=float)

TypeError: ones() got an unexpected keyword argument 'type'

In [26]:
# create a 3*5 floating-point array filled with 1s 
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# create a 3*5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [28]:
np.twos((3, 5), dtype=float)

AttributeError: module 'numpy' has no attribute 'twos'

In [29]:
np.two((3, 5), dtype=float)

AttributeError: module 'numpy' has no attribute 'two'

In [30]:
#create  an array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
#this is similar to the built-in range-function
np.arrange(0, 20, 2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [31]:
#create  an array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
#this is similar to the built-in range-function
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
#create an array of 5 values evenly spaced between 0and1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.arange(0, 1, 5)

array([0])

In [34]:
np.linspace(0, 1, 2)

array([0., 1.])

In [35]:
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [36]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
#create a 3*3 array of uniformally distributed random values
#with mean 0 and standard deviation 1
np.random.normal(0, 1, (3*3))

array([ 1.1568999 , -3.51342518, -1.52493477, -1.07534454, -0.15954592,
        1.09769431,  1.23791867,  1.53013427, -0.18522349])

In [38]:
#create a 3*3 array of uniformally distributed random values
#with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-2.85428193, -0.55702203,  0.36969298],
       [-0.16309235,  0.62372846, -0.20632845],
       [-0.95690876,  0.0567933 ,  0.09301407]])

In [39]:
#create a 3*3 array of uniformally distributed random values
#with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.46425211,  0.70790016,  0.28660966],
       [-0.99522105,  0.44495222, -0.73946067],
       [-0.50036674, -0.6526267 ,  0.72215317]])

In [40]:
#create a 3*3 array of uniformly distributed
#random values between 0 and 1
np.random((3, 3))

TypeError: 'module' object is not callable

In [41]:
#create a 3*3 array of uniformly distributed
#random values between 0 and 1
np.random.random((3, 3))

array([[0.57294011, 0.77539762, 0.21632575],
       [0.51693783, 0.42125633, 0.33683182],
       [0.62687714, 0.087116  , 0.60987503]])

In [42]:
#create a 3*3 array of random integers in the interval [0, 10]
np.random.randit(0, 10, (3, 3))

AttributeError: module 'numpy.random' has no attribute 'randit'

In [43]:
#create a 3*3 array of uniformly distributed
#random values between 0 and 1
np.random.randomit((3, 3))

AttributeError: module 'numpy.random' has no attribute 'randomit'

In [44]:
#create a 3*3 array of uniformly distributed
#random values between 0 and 1
np.random.randit((3, 3))

AttributeError: module 'numpy.random' has no attribute 'randit'

In [45]:
#create a 3*3 array of uniformly distributed
#random values between 0 and 1
np.random.randit(0, 10, (3, 3))

AttributeError: module 'numpy.random' has no attribute 'randit'

In [46]:
#create a 3*3 array of uniformly distributed
#random values between 0 and 1
np.random.randint(0, 10, (3, 3))

array([[7, 4, 2],
       [3, 4, 4],
       [2, 5, 8]])

In [47]:
#create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
#create an uninitialized array of three integers
#the values will be whatever happens to already exist at that
#memory location
np.empty(3)

array([1., 1., 1.])

In [49]:
np.random.randint(0, 10, (3, 3))

array([[8, 9, 2],
       [0, 3, 7],
       [1, 2, 6]])

In [50]:
np.empty(3)

array([1., 1., 1.])

In [51]:
np.arange(0, 10, (3*3))

array([0, 9])

In [52]:
np.arange(0, 10, (3, 3))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [53]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.empty(3)

array([1., 1., 1.])

In [55]:
print('x3 ndim: ', x3.ndim)

NameError: name 'x3' is not defined

In [56]:
np,random.seed(0) #seed for reproductivity

x1 = np.rando.randomint(10, size=6) #1 dimension array
x2 = np.random.randomint(10, size=(3, 4)) #2 dimension array
x3 = np.ransom.ransomint(10, size(3, 4, 5)) #3 dimension array

NameError: name 'random' is not defined

In [57]:
np.random.seed(0) #seed for reproductivity

x1 = np.rando.randomint(10, size=6) #1 dimension array
x2 = np.random.randomint(10, size=(3, 4)) #2 dimension array
x3 = np.ransom.ransomint(10, size(3, 4, 5)) #3 dimension array

AttributeError: module 'numpy' has no attribute 'rando'

In [58]:
np.random.seed(0) #seed for reproductivity

x1 = np.random.randomint(10, size=6) #1 dimension array
x2 = np.random.randomint(10, size=(3, 4)) #2 dimension array
x3 = np.ransom.ransomint(10, size(3, 4, 5)) #3 dimension array

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [59]:
import numpy as np
np.random.seed(0) #seed for reproductivity

x1 = np.random.randomint(10, size=6) #1 dimension array
x2 = np.random.randomint(10, size=(3, 4)) #2 dimension array
x3 = np.ransom.randomint(10, size(3, 4, 5)) #3 dimension array

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [60]:
np.random.seed(0) #seed for reproductivity

x1 = np.random.randint(10, size=6) #1 dimension array
x2 = np.random.randint(10, size=(3, 4)) #2 dimension array
x3 = np.ransom.randint(10, size(3, 4, 5)) #3 dimension array

AttributeError: module 'numpy' has no attribute 'ransom'

In [61]:
np.random.seed(0) #seed for reproductivity

x1 = np.random.randint(10, size=6) #1 dimension array
x2 = np.random.randint(10, size=(3, 4)) #2 dimension array
x3 = np.random.randint(10, size(3, 4, 5)) #3 dimension array

NameError: name 'size' is not defined

In [62]:
np.random.seed(0) #seed for reproductivity

x1 = np.random.randint(10, size=6) #1 dimension array
x2 = np.random.randint(10, size=(3, 4)) #2 dimension array
x3 = np.random.randint(10, size=(3, 4, 5)) #3 dimension array

In [63]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [64]:
no.random.randomint(10)

NameError: name 'no' is not defined

In [65]:
np.random.randomint(10)

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [66]:
no.random.randint(10)

NameError: name 'no' is not defined

In [67]:
np.random.randint(10)

4

In [68]:
np.random.randint(10, size=6)

array([3, 4, 4, 8, 4, 3])

In [69]:
np.random.randint(10)

7

In [70]:
np.random.randint(10, size=(3, 4))

array([[5, 5, 0, 1],
       [5, 9, 3, 0],
       [5, 0, 1, 2]])

In [71]:
np.random.randint(10, size=(3, 4, 5))

array([[[4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0],
        [2, 7, 2, 9, 2],
        [3, 3, 2, 3, 4]],

       [[1, 2, 9, 1, 4],
        [6, 8, 2, 3, 0],
        [0, 6, 0, 6, 3],
        [3, 8, 8, 8, 2]],

       [[3, 2, 0, 8, 8],
        [3, 8, 2, 8, 4],
        [3, 0, 4, 3, 6],
        [9, 8, 0, 8, 5]]])

In [72]:
np.random.randint(10, size=(3, 4, 1))

array([[[9],
        [0],
        [9],
        [6]],

       [[5],
        [3],
        [1],
        [8]],

       [[0],
        [4],
        [9],
        [6]]])

In [73]:
print('dtype: ', x3.dtype)

dtype:  int32


In [74]:
print('itemsize: ', x3.itemsize, 'bytes')

itemsize:  4 bytes


In [75]:
print('nbytes: ', x3.nbytes, 'bytes')

nbytes:  240 bytes


In [76]:
print('dtype: ', x1.dtype)

dtype:  int32


In [77]:
print('itemsize: ', x1.itemsize, 'bytes')

itemsize:  4 bytes


In [78]:
x1

array([5, 0, 3, 3, 7, 9])

In [79]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [80]:
x1[0]

5

In [81]:
x1[4]

7

In [82]:
x1[-1]

9

In [83]:
x1[-2]

7

In [84]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [85]:
x3[0, 0, 0]

8

In [86]:
x3[0,1,0]

9

In [87]:
x[1, 0, 0]

NameError: name 'x' is not defined

In [88]:
x3[1, 0, 0]

0

In [89]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [90]:
x2[1, 0]

7

In [91]:
x2[0, -1]

4

In [92]:
x2[2, 3] = 0

In [93]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 0]])

In [94]:
x2[0, 0] = 0

In [95]:
x2

array([[0, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 0]])

In [96]:
x2[2, 3] = 9

In [97]:
x2

array([[0, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 9]])

In [98]:
x1[0] = 3.1415926535 #this will be truncated
x1

array([3, 0, 3, 3, 7, 9])

In [99]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x[:5] #first 5 elements

array([0, 1, 2, 3, 4])

In [101]:
x[2:5] 

array([2, 3, 4])

In [102]:
x[5:] #first 5 elements

array([5, 6, 7, 8, 9])

In [103]:
x[::3] 

array([0, 3, 6, 9])

In [104]:
x[2::3]

array([2, 5, 8])

In [105]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [106]:
x[5::-2]

array([5, 3, 1])

In [107]:
x2

array([[0, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 9]])

In [108]:
x2[:2, :3]

array([[0, 5, 2],
       [7, 6, 8]])

In [109]:
x2[:2:3]

array([[0, 5, 2, 4]])

In [110]:
x1
x1[:2:3]

array([3])

In [111]:
x1

array([3, 0, 3, 3, 7, 9])

In [112]:
x1[2] = 1
x1[3] = 5

In [113]:
x1

array([3, 0, 1, 5, 7, 9])

In [114]:
x1[:2:3]

array([3])

In [115]:
x2[:2:]

array([[0, 5, 2, 4],
       [7, 6, 8, 8]])

In [116]:
x2

array([[0, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 9]])

In [117]:
x2[::3]

array([[0, 5, 2, 4]])

In [118]:
x2[::2]

array([[0, 5, 2, 4],
       [1, 6, 7, 9]])

In [119]:
x2[:2:3]

array([[0, 5, 2, 4]])

In [120]:
x2[:2:5]

array([[0, 5, 2, 4]])

In [121]:
x2[0]

array([0, 5, 2, 4])

In [126]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [128]:
np.random.random(10)

array([0.66017354, 0.29007761, 0.61801543, 0.4287687 , 0.13547406,
       0.29828233, 0.56996491, 0.59087276, 0.57432525, 0.65320082])

In [129]:
x2

array([[0, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 9]])

In [130]:
x2[:2 ,::1]

array([[0, 5, 2, 4],
       [7, 6, 8, 8]])

In [131]:
x2[0, :]

array([0, 5, 2, 4])

In [132]:
x2[:, 0]

array([0, 7, 1])

In [133]:
print(x2)

[[0 5 2 4]
 [7 6 8 8]
 [1 6 7 9]]


In [134]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[0 5]
 [7 6]]


In [135]:
x2_[0, 0] = 99
print(x2_sub)

NameError: name 'x2_' is not defined

In [1]:
x2_sub[0, 0] = 99
print(x2_sub)

NameError: name 'x2_sub' is not defined

In [2]:
x2_sub = x2[:2, :2]
print(x2_sub)

NameError: name 'x2' is not defined

In [3]:
print(x2)

NameError: name 'x2' is not defined

In [4]:
x2

NameError: name 'x2' is not defined

In [5]:
x2 = np.random.randit(10, size=(3, 4))

NameError: name 'np' is not defined

In [6]:
import np as numpy

ModuleNotFoundError: No module named 'np'

In [7]:
import numpy as np

In [8]:
x2 = np.random.randit(10, size=(3, 4))

AttributeError: module 'numpy.random' has no attribute 'randit'

In [9]:
x2 = np.random.randint(10, size=(3, 4))

In [10]:
print(x2)

[[5 2 5 5]
 [0 8 2 9]
 [4 0 1 3]]


In [11]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 2]
 [0 8]]


In [12]:
x2_sub[0, 0 ] = 99
print(x2_sub)

[[99  2]
 [ 0  8]]


In [15]:
print(x2_sub)

[[99  2]
 [ 0  8]]


In [16]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  2]
 [ 0  8]]


In [17]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
x =  np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [19]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [24]:
z = [12, 456, 78]
print(np.concatenate([x, y, z]))

[  1   2   3   4   5   6  12 456  78]


In [25]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [26]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [29]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [4 5] [6 7 8]


In [31]:
x1, x2, x3 = np.split(x, [2, 5])
print(x1, x2, x3)

[1 2] [3 4 5] [6 7 8]


In [32]:
x1, x2, x3 = np.split(x, [3, 4])
print(x1, x2, x3)

[1 2 3] [4] [5 6 7 8]


In [34]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [44]:
u, m1, m2, l = np.vsplit(grid, [1, 2, 3])
print(u)
print(m1)
print(m2)
print(l)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
