In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)
#上記一行の実行時間を計測

2.16 s ± 609 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit(1.0 / big_array)

3.42 ms ± 56 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
x = np.arange(4)
print('x  =', x)
print('x + 5 =', x + 5)
print('x - 5 =', x - 5)
print('x * 5 =', x * 5)
print('x / 5 =', x / 5)
print('x // 5 =', x // 5)

x  = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 5 = [ 0  5 10 15]
x / 5 = [0.  0.2 0.4 0.6]
x // 5 = [0 0 0 0]


In [5]:
print('-x =', -x)
print('x ** 2 =', x ** 2)
print('x % 2 =', x % 2)

-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [7]:
x

array([0, 1, 2, 3])

In [8]:
np.add(x, 2)

array([2, 3, 4, 5])

In [10]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [16]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [24]:
theta = np.linspace(0, np.pi, 3)
print('theta = ', theta)
print('sin(theta) = ', np.sin(theta))
print('cos(theta) = ', np.cos(theta))
print('sin(theta) = ', np.sin(theta))
print('tan(theta) = ', np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [26]:
x = np.arange(5)
y = np.arange(5)
np.multiply(x, 10, out=y)
print(y)

[ 0 10 20 30 40]
